version: '3'

services:
  php:
    image: php7.2-apache
    volumes:
      - ./server:/var/www/html
    ports:
      - 8000:80
    container_name: php7.2-apache

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    container_name: mysql5.7